version: '3.3'
services:
  axonserver-1:
    image: docker.axoniq.io/axoniq/axonserver:latest
    pull_policy: always
    hostname: axonserver-1
    environment:
      - axoniq_console_authentication=${AXONIQ_CONSOLE_AUTHENTICATION}
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-server

  mongodb:
    image: mongo:latest
    container_name: kyc-mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=kyc_db
    volumes:
      - mongodb-data:/data/db
    networks:
      - axon-server

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  axon-server:

volumes:
  mongodb-data:

